### ISSUE TITLE
GLPI webservices over HTTPS with self-signed CA

### ISSUE THREAD

**Issue by pszafer** [shinken-monitoring/mod-auth-ws-glpi#2]
Hello,

OS: Debian 8.0

In my environment we run glpi over https and http disabled.
It is signed by self-signed CA.

I added certificate and CA to ca-trust and run 

`dpkg-reconfigure ca-certificates`

Running module auth-ws-glpi I got error:

```
[1460968237] ERROR: [broker-master] [auth-ws-glpi] Authentication failed: Traceback (most recent call last):
  File "/var/lib/shinken/modules/auth-ws-glpi/module.py", line 83, in check_auth
    result = self.ws_connection.glpi.doLogin(arg)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1301, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1448, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1212, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

Then I tried run it manually from python shell:

```
import xmlrpclib
ws_conn = xmlrpclib.ServerProxy('https://glpi/plugins/webservices/xmlrpc.php')
arg = {'login_name': 'test', 'login_password': 'test' }
print "Logged as %s" % str(ws_conn.glpi.doLogin(arg))

Logged as {'firstname': 'test', 'session': 'ktnpaft2i20gf5kb3crvbrt267', 'id': '32', 'realname': 'test', 'name': 'test' }
```

Can you tell me what am I doing wrong? 
Maybe user shinken doesn't have access to ca-certificates list?

Thank for help!

**Comment by mohierf** [comment]
@ddurieux: any idea about this problem?

**Comment by pszafer** [comment]
Problem solved.
When adding certs to `/usr/local/share/ca-certificates/` command `update-ca-certificates` doesn't update file permissions for users (maybe a bug in command) and user don't have access to read this CA file.

Need to give permission `chmod 751 yourca.crt`
